In [1]:
# Question 1: program to Write a Python program to convert an array to an ordinary list with the same items. we can use the np.tolist() function

from array import *
def array_list(np):
    nl = np.tolist()
    print(nl)
  
np = array('i', [30,56,89])
array_list(np)

[30, 56, 89]


In [3]:
# Question 2: NumPy program to compute the sum of the diagonal element of a given array.

import numpy as np
n_array = np.array([[23, 45, 67],
                    [12, 51, 4],
                    [6, 8, 11]])
print("Matrix:")
print(n_array)
trace = np.trace(n_array)
print("\nTrace:")
print(trace)

Matrix:
[[23 45 67]
 [12 51  4]
 [ 6  8 11]]

Trace:
85
