In [1]:
# Question 1: program to Write a Python program to convert an array to an ordinary list with the same items. we can use the np.tolist() function

from array import *
def array_list(np):
    nl = np.tolist()
    print(nl)
  
np = array('i', [30,56,89])
array_list(np)

[30, 56, 89]


In [9]:
# Question 2: NumPy program to compute the sum of the diagonal element of a given array.

import numpy as np
A_array = np.array([[23, 45, 67],
                    [12, 51, 4],
                    [6, 8, 11]])
print("Matrix:")
print(A_array)
trace = np.trace(A_array)
print("\nTrace:")
print(trace)

Matrix:
[[23 45 67]
 [12 51  4]
 [ 6  8 11]]

Trace:
85


In [10]:
# Question 3: Given an array of your choice, get all the values higher than X :
print("Matrix:")
print(A_array)
print("Values bigger than 11 =", A_array[A_array>11])

Matrix:
[[23 45 67]
 [12 51  4]
 [ 6  8 11]]
Values bigger than 11 = [23 45 67 12 51]


In [11]:
# Question 4: Given two arrays A&B having the same shape. The task is to apply addition by hand : C is the new array. 

B_array = np.array([[15, 32, 0],
                    [20, 51, 4],
                    [6, 5, 9]])
C=A_array+B_array
print(C)

[[ 38  77  67]
 [ 32 102   8]
 [ 12  13  20]]


In [13]:
# Question 5: Write a NumPy program to subtract the mean of each row of a given matrix.

print("Subtract the mean of each row of the said matrix:\n")
D = C - C.mean(axis=1, keepdims=True)
print(D)

Subtract the mean of each row of the said matrix:

[[-22.66666667  16.33333333   6.33333333]
 [-15.33333333  54.66666667 -39.33333333]
 [ -3.          -2.           5.        ]]
