In [1]:
# Question 1: program to Write a Python program to convert an array to an ordinary list with the same items. we can use the np.tolist() function

from array import *
def array_list(np):
    nl = np.tolist()
    print(nl)
  
np = array('i', [30,56,89])
array_list(np)

[30, 56, 89]


In [3]:
# Question 2: NumPy program to compute the sum of the diagonal element of a given array.

import numpy as np
n_array = np.array([[23, 45, 67],
                    [12, 51, 4],
                    [6, 8, 11]])
print("Matrix:")
print(n_array)
trace = np.trace(n_array)
print("\nTrace:")
print(trace)

Matrix:
[[23 45 67]
 [12 51  4]
 [ 6  8 11]]

Trace:
85


In [ ]:
# Question 3: Given an array of your choice, get all the values higher than X :



In [5]:
# Question 4: Given two arrays A&B having the same shape. The task is to apply addition by hand : C is the new array. 

m_array = np.array([[15, 32, 0],
                    [20, 51, 4],
                    [6, 5, 9]])
c=n_array+m_array
print(c)

[[ 38  77  67]
 [ 32 102   8]
 [ 12  13  20]]


In [ ]:
# Question 5: Write a NumPy program to subtract the mean of each row of a given matrix.

